#!/bin/bash
HELP="Use -su tp generate a startup file, use -sd to perform shutdown operations..."
if test $1 = "-sd"
then
	cd "$HOME/pshutdown"
	pacman -Q > SHUTDOWN.txt

	python checkFiles.py

	echo "        Output File Created... "
	echo ""
	read

	sudo chmod 777 revert
	sudo ./revert
	sudo rm -rf STARTUP.txt
	#sudo rm -rf output.txt
	sudo rm -rf SHUTDOWN.txt
	sudo rm-rf revert
	sudo shutdown -t now
elif test $1 = "-su"
then
	cd "$HOME/pshutdown"
	pacman -Q > STARTUP.txt
else
	echo $HELP
fi
